// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  logs: dynamic(() => import("./Logs")),
  rich_text: dynamic(() => import("./RichText")),
};
